#!/system/bin/sh
# Enable Fast Charging (upto 3500mA)

chmod 666 /sys/class/power_supply/battery/constant_charge_current_max
echo 3500000 > /sys/class/power_supply/battery/constant_charge_current_max
chmod 444 /sys/class/power_supply/battery/constant_charge_current_max
